spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}

logging.level.org.springframework.batch: INFO;

---
batchlog:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batchlog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root1004
      driver-class-name: com.mysql.cj.jdbc.Driver

users:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root1004
      driver-class-name: com.mysql.cj.jdbc.Driver
